import localFont from "next/font/local";
import "./globals.css";
import Navbar from "@/components/navbar";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning={true}>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <div
          className="flex  bg-gradient-to-br
 from-[#16281d] to-[#665e7e] text-white font-sans pr-4 "
        >
          <aside className="min-w-44 p-4 pr-0  py-4 flex flex-col  text-sm "></aside>
          <div className="fixed">
            <Navbar />
          </div>
          <div className="flex-1 min-h-screen p-4">{children}</div>
        </div>
      </body>
    </html>
  );
}
