DROP DATABASE qlphim;

create database qlphim;

use qlphim;

-- Thoi luong tinh theo phut
CREATE TABLE PHIM (
    MaPhim INT AUTO_INCREMENT PRIMARY KEY,
    TenPhim VARCHAR(255),
    TheLoai VARCHAR(255),
    DaoDien VARCHAR(255),
    ThoiLuong INT,
    img VARCHAR(255),
    NgayKhoiChieu DATE,
    NgayKetThuc DATE,
    DoTuoi INT,
    TrangThai INT NOT NULL DEFAULT 1
);

-- Loai phong co 2D, 3D, IMAX
CREATE TABLE PHONG_CHIEU (
    MaPhong INT AUTO_INCREMENT PRIMARY KEY,
    TenPhong VARCHAR(100),
    SoGhe INT,
    LoaiPhong VARCHAR(100),
    TrangThai INT NOT NULL DEFAULT 1
);

CREATE TABLE SUAT_CHIEU (
    MaSC INT AUTO_INCREMENT PRIMARY KEY,
    MaPhim INT,
    MaPhong INT,
    NgayChieu DATE,
    GioChieu TIME,
    GiaNguoiLon INT,
    GiaTreEm INT,
    TrangThai INT NOT NULL DEFAULT 1,
    FOREIGN KEY (MaPhim) REFERENCES PHIM(MaPhim),
    FOREIGN KEY (MaPhong) REFERENCES PHONG_CHIEU(MaPhong)
);

CREATE TABLE GHE (
    MaGhePhong VARCHAR(10) PRIMARY KEY,
    MaGhe VARCHAR(6),
    MaPhong INT,
    SoHang INT,
    SoGhe INT,
    LoaiGhe VARCHAR(100),
    TrangThai INT NOT NULL DEFAULT 1,
    FOREIGN KEY (MaPhong) REFERENCES PHONG_CHIEU(MaPhong)
);

CREATE TABLE KHACH_HANG (
    MaKH INT AUTO_INCREMENT PRIMARY KEY,
    TenKH VARCHAR(255),
    SDT VARCHAR(20),
    Email VARCHAR(100)
);

CREATE TABLE VE (
    MaVe INT AUTO_INCREMENT PRIMARY KEY,
    MaSC INT,
    MaKH INT,
    MaGhePhong VARCHAR(10),
    NgayDat DATE,
    GiaVe INT,
    TrangThai VARCHAR(100),
    FOREIGN KEY (MaSC) REFERENCES SUAT_CHIEU(MaSC),
    FOREIGN KEY (MaKH) REFERENCES KHACH_HANG(MaKH),
    FOREIGN KEY (MaGhePhong) REFERENCES GHE(MaGhePhong)
);

CREATE TABLE BAP_NUOC (
    MaCombo INT AUTO_INCREMENT PRIMARY KEY,
    TenCombo VARCHAR(100),
    GiaCombo INT,
    MoTa VARCHAR(255)
);

CREATE TABLE NHAN_VIEN (
    MaNV INT AUTO_INCREMENT PRIMARY KEY,
    HoTenNV VARCHAR(255),
    SDT VARCHAR(20),
    MatKhau VARCHAR(100)
);

CREATE TABLE HOA_DON (
    MaHD INT AUTO_INCREMENT PRIMARY KEY,
    MaKH INT,
    MaNV INT,
    MaCombo INT,
    SoLuongCombo INT,
    NgayMua DATE,
    TongTien INT,
    FOREIGN KEY (MaKH) REFERENCES KHACH_HANG(MaKH),
    FOREIGN KEY (MaNV) REFERENCES NHAN_VIEN(MaNV),
    FOREIGN KEY (MaCombo) REFERENCES BAP_NUOC(MaCombo)
);